version: "3"

volumes:
  db-data:
  redis:
  bundle:
  node_modules:

services:
  web:
    build: .
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
          bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - "bundle:/usr/local/bundle:cached" # 以下up高速化のため
      - "node_modules:/app/node_modules"
      - "/app/vendor"
      - "/app/tmp"
      - "/app/log"
      - "/app/.git"
    ports:
      - 3000:3000
    environment:
      - "DATABASE_PASSWORD=postgres"
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis

  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data
